# Generated by Django 4.1.6 on 2023-02-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useraccount",
            name="email",
        ),
        migrations.AddField(
            model_name="useraccount",
            name="access_code",
            field=models.CharField(default=None, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
